PROJECT_NAME = "Agenas"

PATHS = {
    "data_raw": "data/raw",
    "data_interim": "data/interim",
    "data_processed": "data/processed",
    "data_external": "data/external",
    "metadata": "metadata",
    "downloads_log": "metadata/downloads_log.csv",
    "checksums": "metadata/checksums",
    "data_catalog": "data_catalog/data_catalog.csv",
    "analysis_modules": "data_catalog/analysis_modules.csv",
    "discovered_links": "data_catalog/discovered_links.csv",
    "outputs_figures": "outputs/figures",
    "outputs_tables": "outputs/tables",
    "outputs_reports": "outputs/reports",
    "outputs_dashboard": "outputs/dashboard_data",
}

ANALYSIS_SETTINGS = {
    "default_year": None,
    "min_cell_count": 5,
    "export_csv": True,
    "export_json": True,
    "export_parquet": True,
    "overwrite_existing_files": False,
}

CHART_SETTINGS = {
    "figure_width": 12,
    "figure_height": 7,
    "dpi": 150,
    "default_top_n": 20,
}

QUALITY_SETTINGS = {
    "fail_on_missing_required_columns": False,
    "fail_on_empty_dataset": True,
    "write_quality_reports": True,
}

ANALYSIS_MODULES = [
    {
        "module_id": "mobility_flows",
        "module_name": "Mobilita sanitaria",
        "policy_question": "Da dove partono i pazienti, dove vanno e per quali prestazioni.",
        "priority": "very_high",
        "expected_granularity": "regione_origine_regione_destinazione_prestazione_drg_disciplina_anno",
    },
    {
        "module_id": "mobility_complexity",
        "module_name": "Mobilita per complessita",
        "policy_question": "Separare mobilita di prossimita, bassa complessita e alta specializzazione.",
        "priority": "very_high",
        "expected_granularity": "origine_destinazione_drg_mdc_tipo_ricovero_valore_economico",
    },
    {
        "module_id": "workforce",
        "module_name": "Personale sanitario",
        "policy_question": "Distribuzione di medici, infermieri, OSS e altre professioni per territorio e categoria.",
        "priority": "very_high",
        "expected_granularity": "regione_asl_struttura_professione_categoria_anno",
    },
    {
        "module_id": "waiting_times",
        "module_name": "Tempi di attesa",
        "policy_question": "Tempi di attesa per prestazione, classe di priorita e territorio.",
        "priority": "very_high",
        "expected_granularity": "regione_prestazione_classe_priorita_periodo",
    },
    {
        "module_id": "costs",
        "module_name": "Costi e spesa",
        "policy_question": "Costi, valore della mobilita, spesa e risultati economici per territorio.",
        "priority": "high",
        "expected_granularity": "regione_azienda_voce_costo_anno",
    },
    {
        "module_id": "services",
        "module_name": "Prestazioni",
        "policy_question": "Numero, tipo e distribuzione delle prestazioni sanitarie.",
        "priority": "very_high",
        "expected_granularity": "regione_asl_struttura_prestazione_anno",
    },
    {
        "module_id": "emergency",
        "module_name": "Pronto soccorso",
        "policy_question": "Accessi, codici triage, tempi, esiti e ricoveri da pronto soccorso.",
        "priority": "very_high",
        "expected_granularity": "regione_struttura_triage_esito_periodo",
    },
    {
        "module_id": "hospital_activity",
        "module_name": "Ricoveri e attivita ospedaliera",
        "policy_question": "Volumi, DRG, discipline, degenza e casistica ospedaliera.",
        "priority": "high",
        "expected_granularity": "regione_struttura_drg_disciplina_tipo_ricovero_anno",
    },
]

SOURCES = [
    {
        "source_id": "Agenas_portale_statistico",
        "provider": "Agenas",
        "dataset_name": "Portale Statistico Agenas",
        "theme": "portale_statistico",
        "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "dashboard",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/portale_statistico",
        "enabled": False,
    },
    {
        "source_id": "Agenas_mobilita",
        "provider": "Agenas",
        "dataset_name": "Mobilita sanitaria",
        "theme": "mobility_flows",
        "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "dashboard",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/mobilita",
        "enabled": False,
    },
    {
        "source_id": "Agenas_mobilita_economica",
        "provider": "Agenas",
        "dataset_name": "Risultati economici della mobilita",
        "theme": "costs",
        "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "dashboard",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/mobilita_economica",
        "enabled": False,
    },
    {
        "source_id": "Agenas_specialistica_ambulatoriale",
        "provider": "Agenas",
        "dataset_name": "Specialistica ambulatoriale",
        "theme": "services",
        "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "dashboard",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/specialistica_ambulatoriale",
        "enabled": False,
    },
    {
        "source_id": "Agenas_pnla",
        "provider": "Agenas",
        "dataset_name": "Piattaforma Nazionale Liste di Attesa",
        "theme": "waiting_times",
        "source_page_url": "https://www.portaletrasparenzaservizisanitari.it/piattaforma-nazionale-delle-liste-di-attesa/",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "dashboard",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/pnla",
        "enabled": False,
    },
    {
        "source_id": "Agenas_pne",
        "provider": "Agenas",
        "dataset_name": "Programma Nazionale Esiti",
        "theme": "hospital_activity",
        "source_page_url": "https://www.agenas.gov.it/ricerca-e-sviluppo/758-che-cosa-e-pne",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "manual_review",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/pne",
        "enabled": False,
    },
    {
        "source_id": "Agenas_fabbisogno_personale",
        "provider": "Agenas",
        "dataset_name": "Fabbisogno del personale sanitario",
        "theme": "workforce",
        "source_page_url": "https://www.agenas.gov.it/ricerca-e-sviluppo/758-che-cosa-e-pne",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "manual_review",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "Agenas/fabbisogno_personale",
        "enabled": False,
    },
    {
        "source_id": "ministero_salute_open_data",
        "provider": "Ministero della Salute",
        "dataset_name": "Open Data Ministero della Salute",
        "theme": "open_data",
        "source_page_url": "https://www.dati.salute.gov.it/",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "web_page",
        "license": "IODL v2.0",
        "redistribution_allowed": "yes",
        "output_subfolder": "ministero_salute/open_data",
        "enabled": False,
    },
    {
        "source_id": "ministero_salute_personale_ssn",
        "provider": "Ministero della Salute",
        "dataset_name": "Personale e risorse umane SSN",
        "theme": "workforce",
        "source_page_url": "https://www.dati.salute.gov.it/",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "web_page",
        "license": "IODL v2.0",
        "redistribution_allowed": "yes",
        "output_subfolder": "ministero_salute/personale_ssn",
        "enabled": False,
    },
    {
        "source_id": "ministero_salute_sdo",
        "provider": "Ministero della Salute",
        "dataset_name": "Schede di dimissione ospedaliera e ricoveri",
        "theme": "hospital_activity",
        "source_page_url": "https://www.dati.salute.gov.it/",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "web_page",
        "license": "IODL v2.0",
        "redistribution_allowed": "yes",
        "output_subfolder": "ministero_salute/sdo",
        "enabled": False,
    },
    {
        "source_id": "ministero_salute_pronto_soccorso",
        "provider": "Ministero della Salute",
        "dataset_name": "Pronto soccorso ed emergenza urgenza",
        "theme": "emergency",
        "source_page_url": "https://www.dati.salute.gov.it/",
        "download_url_csv": "",
        "download_url_json": "",
        "download_url_xml": "",
        "access_type": "manual_review",
        "license": "da_verificare",
        "redistribution_allowed": "unclear",
        "output_subfolder": "ministero_salute/pronto_soccorso",
        "enabled": False,
    },
]
