PROJECT_NAME = "Agenas"

PATHS = {
    "data_raw": "data/raw",
    "data_interim": "data/interim",
    "data_processed": "data/processed",
    "data_external": "data/external",
    "metadata": "metadata",
    "downloads_log": "metadata/downloads_log.csv",
    "checksums": "metadata/checksums",
    "data_catalog": "data_catalog/data_catalog.csv",
    "analysis_modules": "data_catalog/analysis_modules.csv",
    "discovered_links": "data_catalog/discovered_links.csv",
    "outputs_figures": "outputs/figures",
    "outputs_tables": "outputs/tables",
    "outputs_reports": "outputs/reports",
    "outputs_dashboard": "outputs/dashboard_data",
}

ANALYSIS_SETTINGS = {"default_year": None, "min_cell_count": 5, "export_csv": True, "export_json": True, "export_parquet": False, "overwrite_existing_files": False}
CHART_SETTINGS = {"figure_width": 12, "figure_height": 7, "dpi": 150, "default_top_n": 20}
QUALITY_SETTINGS = {"fail_on_missing_required_columns": False, "fail_on_empty_dataset": True, "write_quality_reports": True}

ANALYSIS_MODULES = [
    {"module_id": "mobility_flows", "module_name": "Mobilita sanitaria", "coverage": "all_available_data", "expected_granularity": "origine_destinazione_prestazione_disciplina_anno_valore_volume"},
    {"module_id": "mobility_complexity", "module_name": "Mobilita per complessita", "coverage": "all_available_data", "expected_granularity": "drg_mdc_tipo_ricovero_disciplina_prestazione_valore_volume"},
    {"module_id": "workforce", "module_name": "Personale sanitario", "coverage": "all_available_data", "expected_granularity": "regione_asl_struttura_professione_categoria_anno"},
    {"module_id": "waiting_times", "module_name": "Tempi di attesa", "coverage": "all_available_data", "expected_granularity": "regione_prestazione_classe_priorita_periodo"},
    {"module_id": "costs", "module_name": "Costi spesa e risultati economici", "coverage": "all_available_data", "expected_granularity": "regione_azienda_voce_costo_anno"},
    {"module_id": "health_expenditure", "module_name": "Spesa sanitaria regionale nominale reale e demografica", "coverage": "all_available_data", "expected_granularity": "regione_anno_voce_spesa_base_contabile_importo_popolazione_deflatore"},
    {"module_id": "demography_denominators", "module_name": "Denominatori demografici", "coverage": "all_available_data", "expected_granularity": "regione_anno_eta_sesso_popolazione_nascite"},
    {"module_id": "price_deflators", "module_name": "Deflatori e prezzi", "coverage": "all_available_data", "expected_granularity": "anno_indice_base_valore"},
    {"module_id": "services", "module_name": "Prestazioni", "coverage": "all_available_data", "expected_granularity": "regione_asl_struttura_prestazione_anno"},
    {"module_id": "emergency", "module_name": "Emergenza urgenza", "coverage": "all_available_data", "expected_granularity": "regione_struttura_triage_esito_periodo"},
    {"module_id": "hospital_activity", "module_name": "Ricoveri e attivita ospedaliera", "coverage": "all_available_data", "expected_granularity": "regione_struttura_drg_disciplina_tipo_ricovero_anno"},
    {"module_id": "territorial_care", "module_name": "Assistenza territoriale", "coverage": "all_available_data", "expected_granularity": "regione_asl_distretto_servizio_anno"},
    {"module_id": "equipment", "module_name": "Dotazioni e grandi apparecchiature", "coverage": "all_available_data", "expected_granularity": "regione_asl_struttura_apparecchiatura_anno"},
    {"module_id": "structures", "module_name": "Strutture sanitarie", "coverage": "all_available_data", "expected_granularity": "regione_asl_struttura_tipo_accreditamento_anno"},
    {"module_id": "pharmaceutical", "module_name": "Farmaci e assistenza farmaceutica", "coverage": "all_available_data", "expected_granularity": "regione_farmaco_classe_spesa_consumo_anno"},
    {"module_id": "demography", "module_name": "Demografia e denominatori", "coverage": "all_available_data", "expected_granularity": "comune_regione_eta_sesso_anno"},
    {"module_id": "surveillance", "module_name": "Sorveglianze ISS", "coverage": "all_available_data", "expected_granularity": "regione_eta_sesso_periodo_indicatore"},
    {"module_id": "risk_factors", "module_name": "Fattori di rischio e prevenzione", "coverage": "all_available_data", "expected_granularity": "regione_eta_sesso_indicatore_anno"},
]

SOURCES = [
    {"source_id": "Agenas_portale_statistico", "provider": "Agenas", "dataset_name": "Portale Statistico Agenas", "theme": "all", "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "dashboard", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/portale_statistico", "enabled": False},
    {"source_id": "Agenas_mobilita", "provider": "Agenas", "dataset_name": "Mobilita sanitaria", "theme": "mobility_flows", "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "dashboard", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/mobilita", "enabled": False},
    {"source_id": "Agenas_mobilita_economica", "provider": "Agenas", "dataset_name": "Risultati economici della mobilita", "theme": "costs", "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "dashboard", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/mobilita_economica", "enabled": False},
    {"source_id": "Agenas_specialistica_ambulatoriale", "provider": "Agenas", "dataset_name": "Specialistica ambulatoriale", "theme": "services", "source_page_url": "https://stat.agenas.it/web/index.php?r=site%2Fpublic", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "dashboard", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/specialistica_ambulatoriale", "enabled": False},
    {"source_id": "Agenas_pnla", "provider": "Agenas", "dataset_name": "Piattaforma Nazionale Liste di Attesa", "theme": "waiting_times", "source_page_url": "https://www.portaletrasparenzaservizisanitari.it/piattaforma-nazionale-delle-liste-di-attesa/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "dashboard", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/pnla", "enabled": False},
    {"source_id": "Agenas_pne", "provider": "Agenas", "dataset_name": "Programma Nazionale Esiti", "theme": "hospital_activity", "source_page_url": "https://www.agenas.gov.it/ricerca-e-sviluppo/758-che-cosa-e-pne", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "manual_review", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "Agenas/pne", "enabled": False},
    {"source_id": "ministero_salute_open_data", "provider": "Ministero della Salute", "dataset_name": "Open Data Ministero della Salute", "theme": "all", "source_page_url": "https://www.dati.salute.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "IODL v2.0", "redistribution_allowed": "yes", "output_subfolder": "ministero_salute/open_data", "enabled": False},
    {"source_id": "ministero_salute_personale", "provider": "Ministero della Salute", "dataset_name": "Personale SSN", "theme": "workforce", "source_page_url": "https://www.dati.salute.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "IODL v2.0", "redistribution_allowed": "yes", "output_subfolder": "ministero_salute/personale", "enabled": False},
    {"source_id": "ministero_salute_sdo", "provider": "Ministero della Salute", "dataset_name": "Schede dimissione ospedaliera e ricoveri", "theme": "hospital_activity", "source_page_url": "https://www.dati.salute.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "IODL v2.0", "redistribution_allowed": "yes", "output_subfolder": "ministero_salute/sdo", "enabled": False},
    {"source_id": "iss_epicentro", "provider": "ISS", "dataset_name": "EpiCentro ISS", "theme": "surveillance", "source_page_url": "https://www.epicentro.iss.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "iss/epicentro", "enabled": False},
    {"source_id": "iss_respivirnet", "provider": "ISS", "dataset_name": "RespiVirNet", "theme": "surveillance", "source_page_url": "https://www.epicentro.iss.it/sorveglianza-infezioni-respiratorie-acute/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "iss/respivirnet", "enabled": False},
    {"source_id": "iss_passi", "provider": "ISS", "dataset_name": "PASSI", "theme": "risk_factors", "source_page_url": "https://www.epicentro.iss.it/passi/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "iss/passi", "enabled": False},
    {"source_id": "iss_passi_argento", "provider": "ISS", "dataset_name": "PASSI d Argento", "theme": "risk_factors", "source_page_url": "https://www.epicentro.iss.it/passi-argento/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "iss/passi_argento", "enabled": False},
    {"source_id": "iss_okkio", "provider": "ISS", "dataset_name": "OKkio alla SALUTE", "theme": "risk_factors", "source_page_url": "https://www.epicentro.iss.it/okkioallasalute/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "iss/okkio", "enabled": False},
    {"source_id": "istat_demo", "provider": "ISTAT", "dataset_name": "Demografia e popolazione", "theme": "demography", "source_page_url": "https://demo.istat.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "istat/demografia", "enabled": False},
    {"source_id": "istat_population_age_region", "provider": "ISTAT", "dataset_name": "Popolazione residente per eta sesso e territorio", "theme": "demography_denominators", "source_page_url": "https://demo.istat.it/app/?i=POS&l=it", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "istat/demografia/popolazione_eta", "enabled": False},
    {"source_id": "istat_births_region", "provider": "ISTAT", "dataset_name": "Nati vivi per regione", "theme": "demography_denominators", "source_page_url": "https://demo.istat.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "istat/demografia/nascite", "enabled": False},
    {"source_id": "istat_price_deflators", "provider": "ISTAT", "dataset_name": "Indici prezzi e deflatori", "theme": "price_deflators", "source_page_url": "https://www.istat.it/it/archivio/prezzi+al+consumo", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "istat/prezzi", "enabled": False},
    {"source_id": "openbdap_sanita", "provider": "OpenBDAP", "dataset_name": "Spesa sanitaria e finanza SSN", "theme": "costs", "source_page_url": "https://openbdap.rgs.mef.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "openbdap/sanita", "enabled": False},
    {"source_id": "openbdap_api", "provider": "OpenBDAP", "dataset_name": "Catalogo OpenBDAP API CKAN", "theme": "all", "source_page_url": "https://bdap-opendata.rgs.mef.gov.it/content/api", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "ckan_api", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "openbdap/catalogo", "enabled": False},
    {"source_id": "openbdap_ssn_ce_regionale", "provider": "OpenBDAP", "dataset_name": "Conto Economico enti SSN livello regionale", "theme": "health_expenditure", "source_page_url": "https://bdap-opendata.rgs.mef.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "ckan_api", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "openbdap/ssn/conto_economico_regionale", "enabled": False},
    {"source_id": "openbdap_ssn_ce_enti", "provider": "OpenBDAP", "dataset_name": "Conto Economico enti del SSN", "theme": "health_expenditure", "source_page_url": "https://bdap-opendata.rgs.mef.gov.it/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "ckan_api", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "openbdap/ssn/conto_economico_enti", "enabled": False},
    {"source_id": "siope_ssn_movimenti_cassa", "provider": "SIOPE", "dataset_name": "Movimenti di cassa enti SSN", "theme": "health_expenditure", "source_page_url": "https://www.siope.it/Siope/", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "web_page", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "siope/ssn/movimenti_cassa", "enabled": False},
    {"source_id": "aifa_osmed", "provider": "AIFA", "dataset_name": "Rapporti OsMed e farmaci", "theme": "pharmaceutical", "source_page_url": "https://www.aifa.gov.it/rapporti-osmed", "download_url_csv": "", "download_url_json": "", "download_url_xml": "", "access_type": "manual_review", "license": "da_verificare", "redistribution_allowed": "unclear", "output_subfolder": "aifa/osmed", "enabled": False},
]
